### ISSUE TITLE
How can I make this work with netrepl client 

### ISSUE THREAD

**Issue by Inc0n** [sogaiu/ajrepl#1]
I am written a game in janet, so I starts netrepl first then the draw loop.

```
(def s (netrepl/server "0.0.0.0" 9365 env))
(setup)
(draw-loop)
```

And connect using 
```
janet -e "(import spork/netrepl) (netrepl/client)"
```

The problem is it will not function properly and comint to just echo entered text, it may be the prompt, but after changing comint prompt regex to `"^[^ \n]\\[[0-9.]+:[0-9]+\\]:[0-9]+: "`, the same problem persist.

A netrepl prompt looks like this:
```
[127.0.0.1:9365]:1: whatever expression
whatever expression
```

I am out of ideas, and would appreciate some advise on this.

**Comment by sogaiu** [comment]
I haven't looked into netrepl support for ajrepl but there were at least two attempts for using Emacs with `spork/netrepl`:

* https://github.com/yrns/janet-netrepl
* https://github.com/sogaiu/a-janet-spork-client

I haven't tested the former one, but I would guess it would be faster because it uses bindat, whereas the latter one was just trying to get things to work (not much attention paid to efficiency).

**Comment by sogaiu** [comment]
It looks like janet-netrepl uses `set-process-filter-multibyte` which may no longer be in Emacs 29.

From Emacs' [Changelog.3](https://github.com/emacs-mirror/emacs/blob/89e337c3fc9a51454afb86176a507f46c198be9f/ChangeLog.3):

> 2022-08-19  Stefan Kangas  <...>

>	Resurrect obsoletion warning for two functions

>	These were supposed to have been deleted, but never were.  Resurrect
>	their obsoletion warning and let's delete them in Emacs 29 instead.

>	* lisp/subr.el (process-filter-multibyte-p)
>	(set-process-filter-multibyte): Resurrect obsoletion warning.
>	* etc/NEWS: Don't announce their deletion.

**Comment by sogaiu** [comment]
I tried modifying janet-netrepl a bit, but didn't have much luck getting it to work.

`bindat` itself seems to do some kind of multibyte to unibyte conversion and I suppose it's possible this is not working so well with `set-process-coding-system` (which is [commented out](https://github.com/yrns/janet-netrepl/blob/7b7e2893854113493fef2aa6f60136f1de72e339/janet-netrepl.el#L26)).  I'm not really familiar with `bindat` though so the previous statement may be quite off.

May be the author of janet-netrepl would be more informed about the situation.

In some limited testing, the other option (a-janet-spork-client) seemed to still work and that [uses `set-process-coding-system`](https://github.com/sogaiu/a-janet-spork-client/blob/4ae04cda1d14d7aef5780250bfbaa5ebc13dde3f/ajsc.el#L488-L490) without issues AFAICT.

**Comment by Inc0n** [comment]
Thank you this is very informative, I will give [a-janet-spork-client](https://github.com/sogaiu/a-janet-spork-client) a go first then.

**Comment by Inc0n** [comment]
[a-janet-spork-client](https://github.com/sogaiu/a-janet-spork-client) works like a charm :) 🤣 (cry of happy tears)
